server:
  port: 8086

spring:
  application:
    name: digital

  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/digital?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    enabled: true
    path: /openapi/v3/api-docs